name: CurrencyRates with Gradle. CI/CD.

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/*'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/*'
    types:
      - opened
      - edited
      - reopened

env:
  JAVA: '19'
  DISTRIBUTION: 'oracle'
  ARCHITECTURE: x64

jobs:

  clean-and-build-currency-rates-app:
    runs-on: ubuntu-latest
    steps:
      - name: Copy project from repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA }}
          distribution: ${{ env.DISTRIBUTION }}
          architecture: ${{ env.ARCHITECTURE }}
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: release-candidate
      - name: Clean with Gradle
        run: gradle clean
      - name: Build with Gradle
        run: gradle build
      - name: Generate message
        run: echo "The release-candidate version was ${{ steps.setup-gradle.outputs.gradle-version }}"
      - name: Copy jar file
        run: mkdir package && cp ./build/libs/*.jar package
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: package
          name: artifacts
          retention-days: 1

  deploy_currency_rates:
    needs:
      - clean-and-build-currency-rates-app
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts for all modules.
        uses: actions/download-artifact@v4
        with:
          path: package
          name: artifacts