name: CurrencyRates with Gradle. CI/CD. Docker-compose.

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/*'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/*'
    types:
      - opened
      - edited
      - reopened

env:
  JAVA: '19'
  DISTRIBUTION: 'oracle'
  ARCHITECTURE: x64

jobs:

  test_currency_rates:
    runs-on: ubuntu-latest
    steps:
      - name: Copy project from repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA }}
          distribution: ${{ env.DISTRIBUTION }}
          architecture: ${{ env.ARCHITECTURE }}
          cache: gradle
      - name: Run project`s tests
        run: gradle test

  prepare-environment:
    runs-on: self-hosted
    needs: test_currency_rates
    steps:
      - name: Copy project from repository
        uses: actions/checkout@v4
      - name: Stop and remove containers, networks
        run: docker-compose down
      - name: Delete all images
        run: docker system prune -a -f

  deploy:
    needs: prepare-environment
    runs-on: self-hosted
    steps:
      - name: Create images and run containers
        run: docker-compose up -d